version: "3.8"

services:
  app:
    image: mariana1203/cn2-agendatec:latest
    ports:
      - "5001:5000"
    networks:
      - backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:admin1234@db:5432/cetech
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: cetech
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.hostname == worker1

networks:
  backend:

volumes:
  db_data:
